# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [20]:
import torch

Construct a 5x3 matrix, uninitialized

In [40]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.4013e-45, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 2.0000e+00],
        [0.0000e+00, 2.0000e+00, 4.7339e+30],
        [5.8337e-10, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix

In [41]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3761, 0.1608, 0.4185],
        [0.4369, 0.7306, 0.2791],
        [0.8756, 0.1488, 0.5611],
        [0.8975, 0.3751, 0.6716],
        [0.4441, 0.0994, 0.9897]])


Get its size

In [23]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [24]:
x[1:3] = 2
print(x)

tensor([[0.9052, 0.4413, 0.3326],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.6180, 0.0488, 0.2516],
        [0.5620, 0.1107, 0.1773]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [25]:
#1
x1=torch.Tensor(2,17)
#2
x2=torch.FloatTensor(3,1)
#3
x3=torch.LongTensor(5,2,1)
x3[:]=7
#4
x4=torch.ByteTensor(5,)
x4[1:4]=1
x4

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [27]:
x

tensor([[0.9052, 0.4413, 0.3326],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.6180, 0.0488, 0.2516],
        [0.5620, 0.1107, 0.1773]])

In [29]:
y = torch.rand(5, 3)
print(y)
print(x + y)

tensor([[0.8058, 0.8159, 0.1955],
        [0.6683, 0.4042, 0.1042],
        [0.8665, 0.1091, 0.5259],
        [0.2084, 0.4312, 0.2953],
        [0.7036, 0.0990, 0.9476]])
tensor([[1.7110, 1.2572, 0.5281],
        [2.6683, 2.4042, 2.1042],
        [2.8665, 2.1091, 2.5259],
        [0.8264, 0.4800, 0.5468],
        [1.2655, 0.2096, 1.1249]])


### 2.2 Addition: syntax 2

In [30]:
print(torch.add(x, y))

tensor([[1.7110, 1.2572, 0.5281],
        [2.6683, 2.4042, 2.1042],
        [2.8665, 2.1091, 2.5259],
        [0.8264, 0.4800, 0.5468],
        [1.2655, 0.2096, 1.1249]])


### 2.3 Addition: giving an output tensor

In [31]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.7110, 1.2572, 0.5281],
        [2.6683, 2.4042, 2.1042],
        [2.8665, 2.1091, 2.5259],
        [0.8264, 0.4800, 0.5468],
        [1.2655, 0.2096, 1.1249]])


### 2.4 Addition: in-place

adds `x`to `y`

In [32]:
y.add_(x)
print(y)

tensor([[1.7110, 1.2572, 0.5281],
        [2.6683, 2.4042, 2.1042],
        [2.8665, 2.1091, 2.5259],
        [0.8264, 0.4800, 0.5468],
        [1.2655, 0.2096, 1.1249]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [35]:
print(x)
print(x[:, 1])

tensor([[0.9052, 0.4413, 0.3326],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.6180, 0.0488, 0.2516],
        [0.5620, 0.1107, 0.1773]])
tensor([0.4413, 2.0000, 2.0000, 0.0488, 0.1107])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [44]:
x=torch.rand(4,4)
y=torch.rand(4,4)
print(x)
print(y)

#1
print(x.mul_(y))
#2
print(x * y)


tensor([[0.0831, 0.8622, 0.8975, 0.2964],
        [0.3538, 0.8692, 0.1703, 0.0820],
        [0.5751, 0.0556, 0.7391, 0.6293],
        [0.3827, 0.8688, 0.9468, 0.1170]])
tensor([[0.5208, 0.3117, 0.2313, 0.4086],
        [0.3153, 0.1143, 0.4340, 0.2760],
        [0.2387, 0.5254, 0.5031, 0.3698],
        [0.9126, 0.9744, 0.0646, 0.1212]])
tensor([[0.0433, 0.2687, 0.2076, 0.1211],
        [0.1116, 0.0994, 0.0739, 0.0226],
        [0.1372, 0.0292, 0.3719, 0.2327],
        [0.3493, 0.8466, 0.0612, 0.0142]])
tensor([[0.0225, 0.0838, 0.0480, 0.0495],
        [0.0352, 0.0114, 0.0321, 0.0062],
        [0.0328, 0.0153, 0.1871, 0.0861],
        [0.3187, 0.8249, 0.0040, 0.0017]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [45]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [46]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [47]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [48]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [49]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
